name: PR integration tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [1.8, 15]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-jdk${{ matrix.jdk }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-jdk${{ matrix.jdk }}-maven-
    - name: Check formatting
      run: mvn -B formatter:validate impsort:check xml-format:xml-check
    - name: Build
      run: mvn -B -T 2 clean install -Pquick,\!formatting -Dmaven.javadoc.skip=true -Djapicmp.skip -Denforcer.skip=true -Danimal.sniffer.skip=true
    - name: Verify
      run: mvn -B verify -PskipUnitTests,\!formatting -Dmaven.javadoc.skip=true -Djapicmp.skip -Denforcer.skip=true -Danimal.sniffer.skip=true
    - name: Print test failures
      if: failure()
      run: ./scripts/printTestResults.sh

