name: PR verify

on: pull_request

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        cache: 'maven'
    - name: Check formatting
      run: mvn -B formatter:validate impsort:check xml-format:xml-check
    - name: Cancel workflow on failure
      uses: vishnudxb/cancel-workflow@v1.2
      if: failure()
      with:
        repo: eclipse/rdf4j
        workflow_id: ${{ github.run_id }}
        access_token: ${{ github.token }}
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [11, 18]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        cache: 'maven'
    - name: Build
      run: mvn -B -U -T 2 clean install -Pquick,-formatting -Dmaven.javadoc.skip=true -Djapicmp.skip -Denforcer.skip=true -Danimal.sniffer.skip=true
    - name: Test
      run: mvn -B test -P-formatting -DskipITs -Dmaven.javadoc.skip=true
    - name: Publish Test Report
      if: failure()
      uses: scacap/action-surefire-report@v1
      with:
        check_name: Test report - build - ${{ matrix.jdk }}
    - name: Cancel workflow on failure
      uses: vishnudxb/cancel-workflow@v1.2
      if: failure()
      with:
        repo: eclipse/rdf4j
        workflow_id: ${{ github.run_id }}
        access_token: ${{ github.token }}
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        cache: 'maven'
    - name: Build
      run: mvn -B -U -T 2 clean install -Pquick,-formatting -Dmaven.javadoc.skip=true -Djapicmp.skip -Denforcer.skip=true -Danimal.sniffer.skip=true
    - name: Verify
      run: mvn -B verify -PskipUnitTests,-formatting -Dmaven.javadoc.skip=true -Denforcer.skip=true -Danimal.sniffer.skip=true
    - name: Publish Test Report
      if: failure()
      uses: scacap/action-surefire-report@v1
      with:
        check_name: Test report - integration-tests
    - name: Cancel workflow on failure
      uses: vishnudxb/cancel-workflow@v1.2
      if: failure()
      with:
        repo: eclipse/rdf4j
        workflow_id: ${{ github.run_id }}
        access_token: ${{ github.token }}
  slow-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        cache: 'maven'
    - name: Build
      run: mvn -B -U -T 2 clean install -Pquick,-formatting -Dmaven.javadoc.skip=true -Djapicmp.skip -Denforcer.skip=true -Danimal.sniffer.skip=true
    - name: Verify
      run: mvn -B verify -PslowTestsOnly,-skipSlowTests,-formatting -Dmaven.javadoc.skip=true -Djapicmp.skip -Denforcer.skip=true -Danimal.sniffer.skip=true
    - name: Publish Test Report
      if: failure()
      uses: scacap/action-surefire-report@v1
      with:
        check_name: Test report - slow-tests
  copyright-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check copyright header present
      run: scripts/checkCopyrightPresent.sh
